/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Session layer for LangReport.
 */
public class LangReportSession
   extends assesment.persistence.language.LangReportBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
