/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Local home interface for LangReport.
 */
public interface LangReportLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LangReportLocal";
   public static final String JNDI_NAME="LangReportLocal";

   public assesment.persistence.language.LangReportLocal create()
      throws javax.ejb.CreateException;

}
