/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Home interface for LangReport.
 */
public interface LangReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LangReport";
   public static final String JNDI_NAME="ejb/LangReport";

   public assesment.persistence.language.LangReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
