/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Remote interface for LangABM.
 */
public interface LangABM
   extends javax.ejb.EJBObject
{

   public void saveText( java.lang.String key,java.lang.String language,java.lang.String text,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateText( java.lang.String key,java.lang.String language,java.lang.String text,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
