/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Remote interface for LangReport.
 */
public interface LangReport
   extends javax.ejb.EJBObject
{

   public java.lang.Object[][] findMessages( java.util.Locale locale )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection findAllLanguage(  )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.HashMap findAllNativeMessages(  )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String findText( java.lang.String key,java.lang.String language,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String[] findTexts( java.lang.String key,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String[] getCompleteText( java.lang.String key,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;
   
   public java.lang.Object[][] findMessagesbkp( java.util.Locale locale )
		      throws java.lang.Exception, java.rmi.RemoteException;
   
   public java.lang.String[] findTextsbkp( java.lang.String key,assesment.communication.administration.user.UserSessionData userSessionData )
		      throws java.lang.Exception, java.rmi.RemoteException;
}
