/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Home interface for LangABM.
 */
public interface LangABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LangABM";
   public static final String JNDI_NAME="ejb/LangABM";

   public assesment.persistence.language.LangABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
