/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.language;

/**
 * Local interface for LangReport.
 */
public interface LangReportLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Object[][] findMessages( java.util.Locale locale ) throws java.lang.Exception;

   public java.util.Collection findAllLanguage(  ) throws java.lang.Exception;

   public java.util.HashMap findAllNativeMessages(  ) throws java.lang.Exception;

   public java.lang.Object[][] findMessagesbkp( java.util.Locale locale ) throws java.lang.Exception;

}
