/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.tag;

/**
 * Session layer for TagABM.
 */
public class TagABMSession
   extends assesment.persistence.tag.TagABMBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
