/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.tag;

/**
 * Remote interface for TagABM.
 */
public interface TagABM
   extends javax.ejb.EJBObject
{

   public java.lang.Integer associateAssesment( java.lang.Integer tag,java.lang.Integer assesment,java.lang.Integer min,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer associateAnswer( java.lang.Integer tag,java.lang.Integer answer,java.lang.Integer value,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desassociateAssesment( java.lang.Integer tag,java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desassociateAssesmentQuestion( java.lang.Integer tag,java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desassociateQuestion( java.lang.Integer tag,java.lang.Integer question,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateAnswerTag( java.lang.Integer tag,java.lang.Integer answer,java.lang.Integer value,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
