/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.tag;

/**
 * Home interface for TagABM.
 */
public interface TagABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TagABM";
   public static final String JNDI_NAME="ejb/TagABM";

   public assesment.persistence.tag.TagABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
