/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.corporation;

/**
 * Home interface for CorpABM.
 */
public interface CorpABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CorpABM";
   public static final String JNDI_NAME="ejb/CorpABM";

   public assesment.persistence.corporation.CorpABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
