/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.corporation;

/**
 * Remote interface for CorpABM.
 */
public interface CorpABM
   extends javax.ejb.EJBObject
{

   public java.lang.Integer create( assesment.communication.corporation.CorporationAttributes attributes,assesment.communication.administration.user.UserSessionData userRequest )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.corporation.CorporationAttributes attributes,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.lang.Integer corporationId,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String validateDelete( java.lang.Integer corporation )
      throws java.rmi.RemoteException;

   public java.lang.Integer createCedi( assesment.communication.corporation.CediAttributes attributes,assesment.communication.administration.user.UserSessionData userRequest )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateCedi( assesment.communication.corporation.CediAttributes attributes,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteCedi( java.lang.Integer cediId,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
