/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.corporation;

/**
 * Session layer for CorpABM.
 */
public class CorpABMSession
   extends assesment.persistence.corporation.CorpABMBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
