/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.corporation;

/**
 * Local home interface for CorpReport.
 */
public interface CorpReportLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CorpReportLocal";
   public static final String JNDI_NAME="CorpReportLocal";

   public assesment.persistence.corporation.CorpReportLocal create()
      throws javax.ejb.CreateException;

}
