/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.corporation;

/**
 * Home interface for CorpReport.
 */
public interface CorpReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CorpReport";
   public static final String JNDI_NAME="ejb/CorpReport";

   public assesment.persistence.corporation.CorpReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
