/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.user;

/**
 * Local home interface for UsABMFacade.
 */
public interface UsABMFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UsABMFacadeLocal";
   public static final String JNDI_NAME="UsABMFacadeLocal";

   public assesment.business.administration.user.UsABMFacadeLocal create()
      throws javax.ejb.CreateException;

}
