/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.user;

/**
 * Home interface for UsReportFacade.
 */
public interface UsReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UsReportFacade";
   public static final String JNDI_NAME="ejb/UsReportFacade";

   public assesment.business.administration.user.UsReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
