/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.user;

/**
 * Local home interface for UsABM.
 */
public interface UsABMLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UsABMLocal";
   public static final String JNDI_NAME="UsABMLocal";

   public assesment.persistence.user.UsABMLocal create()
      throws javax.ejb.CreateException;

}
