/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.user;

/**
 * Home interface for UsABM.
 */
public interface UsABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UsABM";
   public static final String JNDI_NAME="ejb/UsABM";

   public assesment.persistence.user.UsABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
