/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.user;

/**
 * Home interface for UsReport.
 * @generated 
 */
public interface UsReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UsReport";
   public static final String JNDI_NAME="ejb/UsReport";

   public assesment.persistence.user.UsReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
