/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.user;

/**
 * Local home interface for UsReport.
 * @generated 
 */
public interface UsReportLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UsReportLocal";
   public static final String JNDI_NAME="UsReportLocal";

   public assesment.persistence.user.UsReportLocal create()
      throws javax.ejb.CreateException;

}
