/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.user;

/**
 * Session layer for UsReport.
 * @generated 
 */
public class UsReportSession
   extends assesment.persistence.user.UsReportBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
