/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.module;

/**
 * Session layer for ModuleABM.
 */
public class ModuleABMSession
   extends assesment.persistence.module.ModuleABMBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
