/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.module;

/**
 * Remote interface for ModuleABM.
 */
public interface ModuleABM
   extends javax.ejb.EJBObject
{

   public java.lang.Integer create( assesment.communication.module.ModuleAttribute attributes,assesment.communication.administration.user.UserSessionData userRequest )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createGeneric( assesment.communication.module.ModuleAttribute attributes,assesment.communication.administration.user.UserSessionData userRequest )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.module.ModuleAttribute attributes,assesment.communication.administration.user.UserSessionData userSessionData,int generic )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.lang.Integer moduleId,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteAll( java.lang.Integer moduleId,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String validateDelete( java.lang.Integer module,int type )
      throws java.rmi.RemoteException;

   public void moveModule( java.lang.Integer moduleId,int action,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
