/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.module;

/**
 * Home interface for ModuleReport.
 */
public interface ModuleReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ModuleReport";
   public static final String JNDI_NAME="ejb/ModuleReport";

   public assesment.persistence.module.ModuleReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
