/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.module;

/**
 * Local home interface for ModuleReport.
 */
public interface ModuleReportLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ModuleReportLocal";
   public static final String JNDI_NAME="ModuleReportLocal";

   public assesment.persistence.module.ModuleReportLocal create()
      throws javax.ejb.CreateException;

}
