/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.module;

/**
 * Home interface for ModuleABM.
 */
public interface ModuleABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ModuleABM";
   public static final String JNDI_NAME="ejb/ModuleABM";

   public assesment.persistence.module.ModuleABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
