/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.tag;

/**
 * Remote interface for TagABMFacade.
 */
public interface TagABMFacade
   extends javax.ejb.EJBObject
{

   public void associateAssesmentTag( java.lang.Integer assesment,java.util.Collection tags,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void associateQuestionTag( java.lang.Integer questionId,java.util.Collection tags,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desassociateAssesmentTag( java.lang.Integer assesment,java.util.Collection tags,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desassociateQuestionTag( java.lang.Integer question,java.util.Collection tags,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateAnswerTag( java.lang.Integer tag,java.lang.Integer answer,java.lang.Integer value,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
