/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.tag;

/**
 * Session layer for TagABMFacade.
 */
public class TagABMFacadeSession
   extends assesment.business.tag.TagABMFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
