/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.tag;

/**
 * Session layer for TagReportFacade.
 */
public class TagReportFacadeSession
   extends assesment.business.tag.TagReportFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
