/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.tag;

/**
 * Home interface for TagReportFacade.
 */
public interface TagReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TagReportFacade";
   public static final String JNDI_NAME="ejb/TagReportFacade";

   public assesment.business.tag.TagReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
