/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.tag;

/**
 * Remote interface for TagReportFacade.
 */
public interface TagReportFacade
   extends javax.ejb.EJBObject
{

   public java.util.Collection getListNotAssociated( java.lang.Integer assesment,assesment.communication.language.Text messages,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getListAssociated( java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getListNotAssociatedQuestion( java.lang.Integer assesment,java.lang.Integer question,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getListAssociatedQuestion( java.lang.Integer question,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String[] getAnswerTag( java.lang.Integer tag,java.lang.Integer answer,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getAssociatedLessons( java.lang.String user,java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getTextAssociatedLessons( java.lang.String user,java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
