/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Session layer for PropertyABMFacade.
 */
public class PropertyABMFacadeSession
   extends assesment.business.administration.property.PropertyABMFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
