/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Home interface for PropertyABMFacade.
 */
public interface PropertyABMFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyABMFacade";
   public static final String JNDI_NAME="ejb/PropertyABMFacade";

   public assesment.business.administration.property.PropertyABMFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
