/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Remote interface for PropertyABMFacade.
 */
public interface PropertyABMFacade
   extends javax.ejb.EJBObject
{

   public void propertyUpdate( assesment.communication.administration.property.PropertyData data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
