/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Home interface for PropertyReportFacade.
 */
public interface PropertyReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyReportFacade";
   public static final String JNDI_NAME="ejb/PropertyReportFacade";

   public assesment.business.administration.property.PropertyReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
