/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Remote interface for PropertyReportFacade.
 */
public interface PropertyReportFacade
   extends javax.ejb.EJBObject
{

   public assesment.communication.administration.property.PropertyData findPropertyByPrimaryKey( java.lang.String propertyPK,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
