/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Local interface for PropertyABMFacade.
 */
public interface PropertyABMFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public void propertyUpdate( assesment.communication.administration.property.PropertyData data,assesment.communication.administration.user.UserSessionData userSessionData ) throws java.lang.Exception;

}
