/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.property;

/**
 * Local home interface for PropertyABMFacade.
 */
public interface PropertyABMFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyABMFacadeLocal";
   public static final String JNDI_NAME="PropertyABMFacadeLocal";

   public assesment.business.administration.property.PropertyABMFacadeLocal create()
      throws javax.ejb.CreateException;

}
