/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.assesment;

/**
 * Home interface for AssesmentABM.
 */
public interface AssesmentABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AssesmentABM";
   public static final String JNDI_NAME="ejb/AssesmentABM";

   public assesment.persistence.assesment.AssesmentABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
