/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.assesment;

/**
 * Home interface for AssesmentReport.
 */
public interface AssesmentReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AssesmentReport";
   public static final String JNDI_NAME="ejb/AssesmentReport";

   public assesment.persistence.assesment.AssesmentReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
