/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.corporation;

/**
 * Home interface for CorpABMFacade.
 */
public interface CorpABMFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CorpABMFacade";
   public static final String JNDI_NAME="ejb/CorpABMFacade";

   public assesment.business.administration.corporation.CorpABMFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
