/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.corporation;

/**
 * Home interface for CorpReportFacade.
 */
public interface CorpReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CorpReportFacade";
   public static final String JNDI_NAME="ejb/CorpReportFacade";

   public assesment.business.administration.corporation.CorpReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
