/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.corporation;

/**
 * Local home interface for CorpReportFacade.
 */
public interface CorpReportFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CorpReportFacadeLocal";
   public static final String JNDI_NAME="CorpReportFacadeLocal";

   public assesment.business.administration.corporation.CorpReportFacadeLocal create()
      throws javax.ejb.CreateException;

}
