/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.corporation;

/**
 * Session layer for CorpABMFacade.
 */
public class CorpABMFacadeSession
   extends assesment.business.administration.corporation.CorpABMFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
