/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.corporation;

/**
 * Remote interface for CorpABMFacade.
 */
public interface CorpABMFacade
   extends javax.ejb.EJBObject
{

   public java.lang.Integer create( assesment.communication.corporation.CorporationAttributes data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.corporation.CorporationAttributes data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createCedi( assesment.communication.corporation.CediAttributes data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateCedi( assesment.communication.corporation.CediAttributes data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteCedi( java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
