/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.administration.corporation;

/**
 * Remote interface for CorpReportFacade.
 */
public interface CorpReportFacade
   extends javax.ejb.EJBObject
{

   public assesment.communication.util.ListResult findCorporationName( java.lang.String name,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.corporation.CorporationData findCorporation( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.corporation.CorporationAttributes findCorporationAttributes( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getPrincipalResume( assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer findCediCode( java.lang.String cedi,java.lang.Integer company,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer[] findCediUser( java.lang.String user,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.corporation.CediAttributes findCediAttributes( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.util.ListResult findCediName( java.lang.String name,java.lang.Integer company,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.corporation.CediData findCedi( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
