/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.question;

/**
 * Local home interface for QuestionReport.
 */
public interface QuestionReportLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionReportLocal";
   public static final String JNDI_NAME="QuestionReportLocal";

   public assesment.persistence.question.QuestionReportLocal create()
      throws javax.ejb.CreateException;

}
