/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.question;

/**
 * Home interface for QuestionReport.
 */
public interface QuestionReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionReport";
   public static final String JNDI_NAME="ejb/QuestionReport";

   public assesment.persistence.question.QuestionReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
