/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.question;

/**
 * Remote interface for QuestionABM.
 */
public interface QuestionABM
   extends javax.ejb.EJBObject
{

   public java.lang.Integer create( assesment.communication.question.QuestionData questionData,assesment.communication.administration.user.UserSessionData userRequest,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateAttributes( assesment.communication.question.QuestionData questionData,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.question.QuestionData questionData,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateAnswerAttributes( assesment.communication.question.AnswerData answerData,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createAnswer( assesment.communication.question.AnswerData answerData,java.lang.Integer questionId,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.lang.Integer questionId,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String validateDelete( java.lang.Integer corporation )
      throws java.rmi.RemoteException;

   public void moveQuestion( java.lang.Integer questionId,int action,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateGroup( java.lang.Integer questionId,java.lang.Integer group,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createVideo( java.lang.String key,java.lang.String language,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
