/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.question;

/**
 * Session layer for QuestionReport.
 */
public class QuestionReportSession
   extends assesment.persistence.question.QuestionReportBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
