/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Remote interface for PropertyABM.
 */
public interface PropertyABM
   extends javax.ejb.EJBObject
{

   public void propertyUpdate( assesment.communication.administration.property.PropertyData data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
