/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Local home interface for PropertyReport.
 * @generated 
 */
public interface PropertyReportLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyReportLocal";
   public static final String JNDI_NAME="PropertyReportLocal";

   public assesment.persistence.administration.property.PropertyReportLocal create()
      throws javax.ejb.CreateException;

}
