/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Home interface for PropertyReport.
 * @generated 
 */
public interface PropertyReportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyReport";
   public static final String JNDI_NAME="ejb/PropertyReport";

   public assesment.persistence.administration.property.PropertyReport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
