/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Home interface for PropertyABM.
 */
public interface PropertyABMHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyABM";
   public static final String JNDI_NAME="ejb/PropertyABM";

   public assesment.persistence.administration.property.PropertyABM create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
