/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Local home interface for PropertyABM.
 */
public interface PropertyABMLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PropertyABMLocal";
   public static final String JNDI_NAME="PropertyABMLocal";

   public assesment.persistence.administration.property.PropertyABMLocal create()
      throws javax.ejb.CreateException;

}
