/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Local interface for PropertyABM.
 */
public interface PropertyABMLocal
   extends javax.ejb.EJBLocalObject
{

   public void propertyUpdate( assesment.communication.administration.property.PropertyData data,assesment.communication.administration.user.UserSessionData userSessionData ) throws java.lang.Exception;

}
