/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.persistence.administration.property;

/**
 * Local interface for PropertyReport.
 * @generated 
 */
public interface PropertyReportLocal
   extends javax.ejb.EJBLocalObject
{

   public assesment.communication.administration.property.PropertyData findPropertyByPrimaryKey( java.lang.String propertyPK,assesment.communication.administration.user.UserSessionData userSessionData ) throws java.lang.Exception;

}
