/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.question;

/**
 * Home interface for QuestionABMFacade.
 */
public interface QuestionABMFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionABMFacade";
   public static final String JNDI_NAME="ejb/QuestionABMFacade";

   public assesment.business.question.QuestionABMFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
