/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.question;

/**
 * Home interface for QuestionReportFacade.
 */
public interface QuestionReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionReportFacade";
   public static final String JNDI_NAME="ejb/QuestionReportFacade";

   public assesment.business.question.QuestionReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
