/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.question;

/**
 * Session layer for QuestionReportFacade.
 */
public class QuestionReportFacadeSession
   extends assesment.business.question.QuestionReportFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
