/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.question;

/**
 * Remote interface for QuestionABMFacade.
 */
public interface QuestionABMFacade
   extends javax.ejb.EJBObject
{

   public void create( assesment.communication.question.QuestionData question,java.lang.String[] questionTexts,java.lang.String[][] answerTexts,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.question.QuestionData data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteList( java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateOrder( assesment.communication.module.ModuleData module,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.question.QuestionData questionData,java.lang.String[] questionTexts,java.lang.String[][] answerTexts,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void copyQuestion( java.lang.Integer module,java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void moveQuestion( java.lang.Integer id,int action,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateGroups( java.util.Collection changes,assesment.communication.administration.user.UserSessionData userSessionData,int type )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createVideo( java.lang.String key,java.lang.String language,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
