/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.question;

/**
 * Local home interface for QuestionReportFacade.
 */
public interface QuestionReportFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionReportFacadeLocal";
   public static final String JNDI_NAME="QuestionReportFacadeLocal";

   public assesment.business.question.QuestionReportFacadeLocal create()
      throws javax.ejb.CreateException;

}
