/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.assesment;

/**
 * Home interface for AssesmentABMFacade.
 */
public interface AssesmentABMFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AssesmentABMFacade";
   public static final String JNDI_NAME="ejb/AssesmentABMFacade";

   public assesment.business.assesment.AssesmentABMFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
