/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.assesment;

/**
 * Local home interface for AssesmentReportFacade.
 */
public interface AssesmentReportFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AssesmentReportFacadeLocal";
   public static final String JNDI_NAME="AssesmentReportFacadeLocal";

   public assesment.business.assesment.AssesmentReportFacadeLocal create()
      throws javax.ejb.CreateException;

}
