/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.assesment;

/**
 * Session layer for AssesmentABMFacade.
 */
public class AssesmentABMFacadeSession
   extends assesment.business.assesment.AssesmentABMFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
