/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.assesment;

/**
 * Remote interface for AssesmentABMFacade.
 */
public interface AssesmentABMFacade
   extends javax.ejb.EJBObject
{

   public java.lang.Integer create( assesment.communication.assesment.AssesmentAttributes data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.assesment.AssesmentAttributes data,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createAccessCode( java.lang.Integer assesment,java.lang.String code,java.lang.Integer number,java.lang.Integer extension,java.lang.String language,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteAccessCode( java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateAccessCodeNumber( java.lang.String code,java.lang.Integer number,java.lang.Integer extension,java.lang.String language,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateFeedback( java.lang.Integer assesment,java.lang.String email,java.util.Collection reports,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteResults( java.lang.Integer assessment,java.util.Collection users,java.lang.Integer type,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteQuestionTestResults( java.lang.Integer assessment,java.util.Collection users,java.lang.Integer type,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void addExistingModule( java.lang.Integer assesment,java.lang.Integer module,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createLink( java.lang.Integer assessmentId,java.lang.String language,java.lang.String firstName,java.lang.String lastName,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createGroup( assesment.communication.assesment.GroupData groupData,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateGroup( assesment.communication.assesment.GroupData groupData,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer createCategory( assesment.communication.assesment.CategoryData categoryData,java.util.Collection assesments,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateCategory( assesment.communication.assesment.CategoryData categoryData,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteCategory( java.lang.Integer categoryId,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void asociateAssesmentCategory( java.lang.Integer category,java.util.Collection assessments,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desasociateAssesmentCategory( java.lang.Integer category,java.util.Collection assessments,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void changeAssesmentGroupDate( java.lang.Integer assessmentId,java.lang.Integer categoryId,java.util.Date start,java.util.Date end,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void changeAssesmentReportView( java.lang.Integer category,java.lang.Integer assesment,java.lang.Integer show,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void backUpAssessment( java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
