/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.language;

/**
 * Session layer for LangReportFacade.
 */
public class LangReportFacadeSession
   extends assesment.business.language.LangReportFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
