/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.language;

/**
 * Session layer for LangABMFacade.
 */
public class LangABMFacadeSession
   extends assesment.business.language.LangABMFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
