/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.language;

/**
 * Home interface for LangABMFacade.
 */
public interface LangABMFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LangABMFacade";
   public static final String JNDI_NAME="ejb/LangABMFacade";

   public assesment.business.language.LangABMFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
