/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.language;

/**
 * Remote interface for LangABMFacade.
 */
public interface LangABMFacade
   extends javax.ejb.EJBObject
{

   public void updateTexts( java.lang.String[] texts,java.lang.String key,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void saveText( java.lang.String key,java.lang.String language,java.lang.String text,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
