/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.language;

/**
 * Remote interface for LangReportFacade.
 */
public interface LangReportFacade
   extends javax.ejb.EJBObject
{

   public java.util.Collection findAllLanguage( assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Object[][] findAllMessages( java.util.Locale locale,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.String[] findTexts( java.lang.String key,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.HashMap findAssessmentBKPTexts( java.lang.Integer assessment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
