/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.language;

/**
 * Home interface for LangReportFacade.
 */
public interface LangReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LangReportFacade";
   public static final String JNDI_NAME="ejb/LangReportFacade";

   public assesment.business.language.LangReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
