
package ws.elearning.assessment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ElearningWSAssessmentService", targetNamespace = "http://assessment.elearning.ws/", wsdlLocation = "http://webservices.cepasafedrive.com/WebServices2/ElearningWSAssessment?wsdl")
public class ElearningWSAssessmentService
    extends Service
{

    private final static URL ELEARNINGWSASSESSMENTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://webservices.cepasafedrive.com/WebServices2/ElearningWSAssessment?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ELEARNINGWSASSESSMENTSERVICE_WSDL_LOCATION = url;
    }

    public ElearningWSAssessmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElearningWSAssessmentService() {
        super(ELEARNINGWSASSESSMENTSERVICE_WSDL_LOCATION, new QName("http://assessment.elearning.ws/", "ElearningWSAssessmentService"));
    }

    /**
     * 
     * @return
     *     returns ElearningWSAssessment
     */
    @WebEndpoint(name = "ElearningWSAssessmentPort")
    public ElearningWSAssessment getElearningWSAssessmentPort() {
        return (ElearningWSAssessment)super.getPort(new QName("http://assessment.elearning.ws/", "ElearningWSAssessmentPort"), ElearningWSAssessment.class);
    }

}
