
package ws.elearning.assessment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ElearningWSAssessment", targetNamespace = "http://assessment.elearning.ws/")
public interface ElearningWSAssessment {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserToCourse", targetNamespace = "http://assessment.elearning.ws/", className = "ws.elearning.assessment.AddUserToCourse")
    @ResponseWrapper(localName = "addUserToCourseResponse", targetNamespace = "http://assessment.elearning.ws/", className = "ws.elearning.assessment.AddUserToCourseResponse")
    public String addUserToCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
