/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.module;

/**
 * Remote interface for ModuleABMFacade.
 */
public interface ModuleABMFacade
   extends javax.ejb.EJBObject
{

   public java.lang.Integer create( java.lang.String[] texts,java.lang.Integer assesment,java.lang.Integer type,java.lang.Integer green,java.lang.Integer yellow,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.lang.Integer create( java.lang.String[] texts,java.lang.Integer assesment,java.lang.Integer type,java.lang.Integer green,java.lang.Integer yellow,int size,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createGeneric( java.lang.String[] texts,java.lang.Integer type,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void update( assesment.communication.module.ModuleAttribute data,assesment.communication.administration.user.UserSessionData userSessionData,int generic )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void delete( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteGeneric( java.util.Collection list,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateOrder( assesment.communication.assesment.AssesmentData assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void copyModule( java.lang.Integer assesment,java.util.Collection genericModules,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void moveModule( java.lang.Integer module,int action,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
