/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.module;

/**
 * Home interface for ModuleABMFacade.
 */
public interface ModuleABMFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ModuleABMFacade";
   public static final String JNDI_NAME="ejb/ModuleABMFacade";

   public assesment.business.module.ModuleABMFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
