/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.module;

/**
 * Session layer for ModuleReportFacade.
 */
public class ModuleReportFacadeSession
   extends assesment.business.module.ModuleReportFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
