/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.module;

/**
 * Local home interface for ModuleReportFacade.
 */
public interface ModuleReportFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ModuleReportFacadeLocal";
   public static final String JNDI_NAME="ModuleReportFacadeLocal";

   public assesment.business.module.ModuleReportFacadeLocal create()
      throws javax.ejb.CreateException;

}
