/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.module;

/**
 * Home interface for ModuleReportFacade.
 */
public interface ModuleReportFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ModuleReportFacade";
   public static final String JNDI_NAME="ejb/ModuleReportFacade";

   public assesment.business.module.ModuleReportFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
