/*
 * Generated by XDoclet - Do not edit!
 */
package assesment.business.module;

/**
 * Remote interface for ModuleReportFacade.
 */
public interface ModuleReportFacade
   extends javax.ejb.EJBObject
{

   public assesment.communication.module.ModuleAttribute findModuleAttributes( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.module.ModuleData findModule( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.util.ListResult findGenericModules( java.lang.String name,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.module.ModuleAttribute findGenericModuleAttributes( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.module.ModuleData findGenericModule( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.module.ModuleData getPsicoModule( assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.module.ModuleData getPersonalDataModule( java.lang.Integer assesment,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

   public assesment.communication.module.ModuleAttribute findModuleAttributesbkp( java.lang.Integer id,assesment.communication.administration.user.UserSessionData userSessionData )
      throws java.lang.Exception, java.rmi.RemoteException;

}
